### ISSUE TITLE
Delay trigerr / fill text

### ISSUE THREAD

**Issue by MarekPro1** [gavalierm/pab-propresenter-arena-bridge#1]
- text je skor kliknuty ako prepisany v resolume a tym vznika zly effekt

**Comment by gavalierm** [comment]
This is because of nature of async world.

All things happend at the same time, so there is no option to handle this properl.y

One thing is delay for trigger, o waiting for succes 201 reponse of upload/put, but this can sagnificantly reduce the performance in huge project.

I can add delays but still it will be no garantie

**Comment by MarekPro1** [comment]
I understand. Between time i found out that I had wrong settings in
resolume that created this.

**Comment by gavalierm** [comment]
I m glad to hear that. If you will have futher questions feel free to reopen.
